### PR TITLE
FIX: UI generation of custom interactions of action properties when it rely on OnGUI callback (ISXB-886) 

### PR DESCRIPTION
**Pull request by bmalrat**
### Description

The action editor was not displaying the content of custom interactions when it's done in IMGUI. [ISXB-886](https://issuetracker.unity3d.com/product/unity/issues/guid/ISXB-886)
jira : https://jira.unity3d.com/browse/ISXB-886

When no custom editor exist the generated UI for enum doesn't work well. The value is lost when save + error in the console.

### Changes made

Added an IMGUIContainer to handle IMGUI UI.
Before the change :
image

After the change :
image

Also added some early exit when IMGUI is not the default to prevent to UI to be drawn twice.

Also fixed the generation of UI for enum which loosed the value when saved. Now it use the index instead of trying to convert the string to the value.

### Testing

Tested the repro project which contain IMGUI UI and buildin interaction in UITK + custom interactions without editor 

### Risk

Only in editor, should be safe

### Checklist

Before review:

- [X ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.	
    - Jira port for the next release set as "Resolved".
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [X ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

### CODE REVIEW

**Comment by Pauliusd01** [comment]
Checking

**Comment by Pauliusd01** [comment]
It seems like I lose focus every time I interact with these fields from the custom interactions, is this a bug or something the user script lacks? I'm leaning towards a bug 😅 
https://github.com/Unity-Technologies/InputSystem/assets/54306142/e39154cd-d191-45cb-8b94-78fc31b37cc7

Also, added @ekcoh for code review, feel free to add someone else if you're busy

**Comment by Pauliusd01** [comment]
For some reason the Axis Deadzone processor is duplicated with your changes. This seems to be the only processor/interaction affected (All settings are completely default, all you have to do is create a new input actions asset and add the processor)
image

**Review by Pauliusd01 — CHANGES_REQUESTED** [review]
Updating status

**Comment by bmalrat** [comment]
> ract with these fields from the custom interactions, is this a bug or something the user script lacks? I'm leaning towards a bug 😅

good catch I missed those ones, processor editor are also InputParameterEditor, I only checked Interaction.
They also have 2 UI Implementation.

**Comment by bmalrat** [comment]
> It seems like I lose focus every time I interact with these fields from the custom interactions, is this a bug or something the user script lacks? I'm leaning towards a bug 😅 https://github.com/Unity-Technologies/InputSystem/assets/54306142/e39154cd-d191-45cb-8b94-78fc31b37cc7
> 
> Also, added @ekcoh for code review, feel free to add someone else if you're busy
thanks I will take a look

**Review by ekcoh — APPROVED** [review]
Code changes LGTM. Do I understand it correctly that the focus issues are still an open issue? It sounds like that might need some attention. I am approving this now given that the code changes looks good but there might be side effects as called out by Paulius?

**Comment by Pauliusd01** [comment]
> Code changes LGTM. Do I understand it correctly that the focus issues are still an open issue? It sounds like that might need some attention. I am approving this now given that the code changes looks good but there might be side effects as called out by Paulius?

We've discussed this with Benoit and decided to make a separate bug for that issue. I've since noticed it also affects some non custom interactions such as the multi tap one, but it is not as a big of a problem there as the custom ones could be. (Bug link: https://jira.unity3d.com/browse/ISX-2074)

**Review by Pauliusd01 — APPROVED** [review]
LGTM, checked that extisting interactions/processors function normally and that the custom ones show up correctly as well.

**Pull request merged**
