### PR TITLE
commit of vive knuckles support using legacy XR input. 

### PR DESCRIPTION
**Pull request by mattdatwork**
This adds vive knuckles support.
no finger tracking added as this is not available under the legacy XR input banner.

### CODE REVIEW

**Review by StayTalm — APPROVED** [review]
Approved on condition that the regex works for other EV versions

**Review by jechter — APPROVED** [review]

**Review by Rene-Damm — CHANGES_REQUESTED** [review]
Needs test.

**Comment by douglas-piconi** [comment]
@mattdatwork can you merge latest develop branch into this branch so that we can get  CI run on it.

**Review by douglas-piconi — APPROVED** [review]

**Review by jackpr-unity — CHANGES_REQUESTED** [review]
- [ ] ~For the sake of those who intend to use this, what's the timeline for Knuckles to be hooked up fully~
- [x] Before moving forward, please accept my PR into your fork: https://github.com/mattdatwork/InputSystem-1/pull/1
- [x] Add gripButton
- [x] Add grip (float value)

Input Debugger Observations with Knuckles EV3
- primary button is driven by "B"
- "A" button drives "grip" input
- both the trackpad and the thumbstick drive "trackpad," "trackpadpressed," and "trackpadtouched"
- ~"grip," "grippressed,"~ "index," "middle," "ring," and "pinky" are not driven

KnucklesActions Scene Observations with Knuckles EV3
- ~under the component action list, only actions that are driven are listed _except for_ secondary button - which does not respond in the input debugger.~
- should grip, the finger values, and the thumbstick be visible here?

**Comment by mattdatwork** [comment]
sure ill do another pass on this probably friday.

**Comment by mattdatwork** [comment]
Added automated test for string verification / device detection.

**Comment by jackpr-unity** [comment]
Need to update the knuckles test scene again due to the controller name change.  Pull this into your branch and then I will approve this PR: https://github.com/mattdatwork/InputSystem-1/pull/2

**Review by jackpr-unity — CHANGES_REQUESTED** [review]
The controller name change messed up the example scene mappings.  Approve this PR to your branch, Matt, and we're good to go: https://github.com/mattdatwork/InputSystem-1/pull/2

**Comment by mattdatwork** [comment]
> The controller name change messed up the example scene mappings. Approve this PR to your branch, Matt, and we're good to go: [mattdatwork#2](https://github.com/mattdatwork/InputSystem-1/pull/2)

done!

@Rene-Damm is this sufficient for you?

**Review by jackpr-unity — APPROVED** [review]

**Pull request merged**
