### PR TITLE
Refresh project to 2021.3.19f1

### PR DESCRIPTION
**Pull request by jamesmcgill**
### Description

Refreshed the project and based now on last 2019 release (2019.4.40f1)

### Changes made

- Remove VSCode package as this now causes warning popup when opening in latest Unity trunk
- Update copyright license year to 2023
- Update project files to open cleanly in 2021.3.19f1 (current latest release of 2021)

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

### CODE REVIEW

**Review by jimon — APPROVED** [review]

**Comment by jimon** [comment]
Rebase on latest develop to fix CI issues

Btw maybe it makes sense to use 2021.3 as project version? 2020.3 goes EOL soon, and 2019.4 is EOL long time ago

**Comment by jamesmcgill** [comment]
Stayed with 2019.4 in the end.
Updating to 2021.3 caused manifest.json updates that break CI for lower versions.
Could have gone with 2020 as CI doesn't run 2019 but if we ever needed to check 2019 (still our min version) these changes might be confusing as upgrading is easy, but downgrading isn't at all.

**Comment by jfreire-unity** [comment]
So 2019.4 is EOL but we still support it. What's the reason for that? 
Also, Is there an alignment for the Unity packages to still support EOL Unity versions? Or is this something that some packages do and some don't?

**Comment by jimon** [comment]
@jfreire-unity package validator (upm-ci thingy) will require a build against 2019.4 otherwise it will fail the promotion, we need a new major package version release to change dependency on 2019.4. It's complicated ...

**Pull request merged**
