### PR TITLE
CHANGE: Remove version defines for profiling.

### PR DESCRIPTION
**Pull request by surfnerd**
### Description

Remove the version defines for profiling.  The changelog does not need to change since there are no functional changes here. 

### Changes made

The profiling.core package is not needed, just use the Unity.Profiling.ProfilerMarker from the main assembly. 

### Testing
Tested locally. 

### Risk

Low risk.

### Checklist

Before review:

~~- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.
    - Jira port for the next release set as "Resolved".~~
~~- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.~~
~~- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.~~

During merge:

- [x] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

### CODE REVIEW

**Review by ekcoh — APPROVED** [review]
Thanks for this PR @surfnerd. Code changes look good to me. We just need to make sure it works fine for the Input System supported Unity range (2019 LTS and forward).

**Comment by surfnerd** [comment]
> Thanks for this PR @surfnerd. Code changes look good to me. We just need to make sure it works fine for the Input System supported Unity range (2019 LTS and forward).

Hey @ekcoh, FYI I tested 2019.4 and Unity 6 locally.

**Review by Pauliusd01 — APPROVED** [review]

**Comment by surfnerd** [comment]
based on my neutron PR, I may need to keep the indirection there. please don't merge just yet.

**Comment by surfnerd** [comment]
based on the new Info i may need to keep the indirection. please don't merge yet

**Comment by surfnerd** [comment]
@ekcoh @Pauliusd01, this is good to go in terms of merging. I just wanted to do an extra check. I appreciate your patience!

**Pull request merged**
