### PR TITLE
FIX: Re-add asset name to window title (ISX-1726).

### PR DESCRIPTION
**Pull request by graham-huws**
### Description

Fix for [ISX-1726](https://jira.unity3d.com/browse/ISX-1726) - Include asset name in window title, matching behaviour from before UITK work.

### Changes made

As above.

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [x] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

### CODE REVIEW

**Comment by Pauliusd01** [comment]
The position of the unsaved changes star symbol (*) is different from what it was before
image

**Review by Pauliusd01 — APPROVED** [review]
Other than the minor change mentioned above seems good to me. Checked: that ProjectWideActions is unaffected, IMGUI version is unaffected, unsaved changes * symbol shows up correctly, checked that unusual symbols (chinese, cyrillic characters) and long names don't break the titling.

**Comment by graham-huws** [comment]
> The position of the unsaved changes star symbol (*) is different from what it was before

Thanks, fixed in d7b7bbd24ab2ea45ee62f7ca734eaba8bf578a4f.

**Review by Pauliusd01 — APPROVED** [review]

**Review by ritamerkl — APPROVED** [review]
Didn't check it in the editor - Looks good to me.

**Pull request merged**
