### PR TITLE
DOCS:Update index.md

### PR DESCRIPTION
**Pull request by Donal-Power**
fixing typo to resolve DOCF-4184

### Description
Fixed user-reported bug in documentation

### Changes made
fixed typo to resolve DOCF-4184

### Notes

_Please write down any additional notes, remove the section if not applicable._

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1943) <br/>All committers have signed the CLA.

**Review by ekcoh — APPROVED** [review]
Thanks for correcting the typo @Donal-Power.

**Comment by ekcoh** [comment]
@duckets Since this seems to be coming from a fork I suggest you incorporate this typo correction into one of your pending documentation branches instead and close this PR without merge. This will reduce overhead of forward/backporting since this change is very small.

**Review by duckets — APPROVED** [review]

**Comment by ekcoh** [comment]
@Donal-Power This PR should be closed right since superceeded by https://github.com/Unity-Technologies/InputSystem/pull/1952?

**Comment by ekcoh** [comment]
I am closing this PR now, feel free to reopen if necessary but I believe this have been superseded by #1952.

**Pull request closed without merging**
