### PR TITLE
NEW: API to parse control paths.

### PR DESCRIPTION
**Pull request by Rene-Damm**
# What?

Adds a new API that wraps around our internal parser for control paths.

```CSharp
foreach (var part in InputControlPath.Parse("<XRController>{LeftHand}/trigger")
{
    Debug.Log(part.layout);
    Debug.Log(part.usages.First());
    Debug.Log(part.name);
}
```

# Why?

XR team needs to programmatically process the bindings in an `.inputactions` asset for use with OpenXR. Rather than them copypasting our internal code to work with paths, makes sense to expose the parsing so that everyone can process our path language where needed.

### CODE REVIEW

**Review by andrew-oc — APPROVED** [review]
The PR looks fine but I'm a little concerned that this API shouldn't really be made public until it's more complete. Calling it a parser while it's internal is fine but for it to be public, I feel it should really be able to report parsing errors.

**Comment by jo-unity** [comment]
Removing myself from review because I don't have time, but @duckets can help review the docs for this one 😊

**Comment by Rene-Damm** [comment]
@andrew-oc 
>should really be able to report parsing errors.

Indeed. Think this goes for the parser in general, even when used internally. Added a [ticket](https://jira.unity3d.com/browse/ISX-530) to our tech debt epic.

**Review by bryandube — APPROVED** [review]
Looks good.  I merged this into a local branch and updated the OpenXR v2 input code to use it and all looks good.

**Review by duckets — APPROVED** [review]
Approved with minor docs amendments

**Pull request merged**
