### PR TITLE
Added InputSystem.runUpdatesInEditMode

### PR DESCRIPTION
**Pull request by StayTalm**
### Description

Added InputSystem.runUpdatesInEditMode option to enable running fixed, dynamic, and before render updates without entering play mode.

### Changes made

Added public accessor to InputSystem.
Cut up IsGamePlayingAndHasFocus into `IsGamePlaying`, `hasInputFocus`, and `shouldRunUpdates` to make it easier to read what we are checking for. This made it so I could avoid overriding IsGamePlaying, since the game isn't playing and I didn't want this API to fake it.
Also added tests and some XMLDoc for the new API.
Also added a Test Scene in the main project to do manual testing. Test scene is located in Assets/QA/Tests/EditMode, and contains a scene, an InputActionAsset, and a few helpers scripts to play with.

### Notes

Tests were predominantly Integration Tests, since I needed to check 'If Setting enabled, whole input system behaviour changed'
No Performance tests.

Kept notes and docs fairly simply, didn't add to manual.  It feels like an advanced use API, and not something 99% of users should be touching directly, so extensive docs didn't seem necessary.

### Checklist

Before review:

- [X] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [X] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [X] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

### CODE REVIEW

**Review by jimon — APPROVED** [review]
This most likely breaks something focus related, aka the behavior that we have in play mode when we transition focus between game view and rest of the editor. Probably needs a QA pass to check if the major pieces are working correctly.

**Comment by StayTalm** [comment]
@stefanunity 
Hello, @jimon is requesting a QA pass, he dropped your name in slack.

This PR adds a new flag that let's a user run Dynamic, Fixed, Before Render updates without entering play mode.  It's going to be used for EditorXR (https://unity.com/editorxr).  I ran the automated tests, and added a few of my own.  I tried toggling it quickly, running it then swapping to play mode, then back to this mode, turning it on while in play mode.

Let me know what you need, not sure what's most fragile here.  Happy to add more automated tests or helper scripts to make testing it easier.  I also have  small standalone project I can upload that maps the entirety of VR Edit mode into a small standalone little project.

**Comment by StayTalm** [comment]
@jimon @Rene-Damm 
I'm getting 4 API Verification failures on Windows, but looking at other PRs (namely this one: https://github.com/Unity-Technologies/InputSystem/pull/1317) these appear to be happening outside my PR, i.e. not my cause.  

Note: I got these tests to pass by doing a local clone of Doc-Tools and making sure to call `git lfs pull`

**Comment by jimon** [comment]
@StayTalm please check the mac build, the doctools failing is only related to windows.

**Comment by StayTalm** [comment]
@jimon I'm not sure what you mean about Mac builds, it was only windows builds that failed, and all CI failures on this PR seem to be related to an existing DocTools issue.

**Comment by jimon** [comment]
@StayTalm sorry confused with another PR where are mac builds failed

**Comment by jimon** [comment]
CI on develop should be fixed now, merging it in.

**Comment by StayTalm** [comment]
Thanks @jimon 
I added a small test scene for @stefanunity 
In Assets/QA/EditMode/TestEditMode.Unity has a couple scripts to move settings into the inspector, and hooks it up to a simple ghost cam: Mouse look, WASD to move, space to reset position, left shift to move faster.  Can be rebound, or bound to a controller but should make it easier to test the non-XR cases.

And in doing so, I found a bunch of things I missed for Mice&Keyboard.  I needed to make a change where sometimes the editor updates keep state and delta state events in the event buffer, much like BeforeRender does.  Tested around with mice, and keyboard and couldn't find anywhere the state would leak or overlap, but this let's dynamic, fixed, or before render updates trigger state changes properly, since the editor update type has it's own state buffer, independent of play mode.  Hope it's an ok change, but makes this flag more significant.

**Comment by StayTalm** [comment]
@jimon 
Build failures are looking unusual again.  A few are the 4 Doc failures from before.
A few others are things like this:
https://yamato.cds.internal.unity3d.com/jobs/130-New%2520Input%2520System/tree/Add-Edit-Mode-Updates/.yamato%252Fupm-ci.yml%2523win_standalone_il2cpp_2019.4/6558857/job
```
Unhandled Exception: System.InvalidOperationException: C++ code builder is unable to build C++ code. In order to build C++ code for Windows Desktop, you must have one of these installed:
        Visual Studio 2015 with C++ compilers and Windows 10 SDK (it cannot build C++ code because it is not installed or missing C++ workload component)
        Visual Studio 2015 installation is found by looking at "SOFTWARE\Microsoft\VisualStudio\14.0_Config\InstallDir" in the registry
        Windows 10 SDK is found by looking at "SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0\InstallationFolder" in the registry
        Visual Studio 2017 (or newer) with C++ compilers and Windows 10 SDK (it cannot build C++ code because it is not installed or missing C++ workload component)
        Visual Studio 2017 (or newer) installation is found using Microsoft.VisualStudio.Setup.Configuration COM APIs
        Windows 10 SDK is found by looking at "SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0\InstallationFolder" in the registry
```
        
        Could I have messed something up here?

**Comment by jimon** [comment]
@StayTalm it's because `package-ci/win10` image recently broke, I've moved `develop` to a pinned version, try merging `develop` into this branch

**Review by andrew-oc — APPROVED** [review]

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1319) before we can accept your contribution.<br/><hr/>**Dmytro Ivanov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/InputSystem?pullRequest=1319) it.</sub>

**Pull request merged**
