### PR TITLE
FIX: Make displayIndex usable for PenState

### PR DESCRIPTION
**Pull request by brice-gros**
### Description

Make displayIndex usable for PenState.

### Changes made

Use the displayIndex from PenState to get the target display

### Testing

Tested on Android 14

### Risk

PenState not working on non-Android platform

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.
    - Jira port for the next release set as "Resolved".
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1976) <br/>All committers have signed the CLA.

**Comment by ekcoh** [comment]
Hi @brice-gros and thanks for opening this draft PR. Are you expecting to do more work on it or have you accidentally not marked it ready for review?

**Review by ekcoh — CHANGES_REQUESTED** [review]
Changes look good, PR only misses an entry in CHANGELOG.md and needs to be updated based on latest develop

**Comment by ekcoh** [comment]
Adding QA to PR. Also would recommend testing Pen on other platforms that targeted platform and for various Unity generations.

**Comment by Pauliusd01** [comment]
I don't have any pen devices, added @stefanunity

**Review by stefanunity — APPROVED** [review]
-I don't have an android with a pen, even less the exact device Brice has
-I tested some pen and touch/pointer input on Windows touch screen and wacom + pen
-nothing bad happened

**Review by ekcoh — APPROVED** [review]
Changes LGTM

**Comment by brice-gros** [comment]
Duplicated in #2057 to get yamato tests running

**Pull request closed without merging**
