### PR TITLE
FIX: ProjectWideActions template Previous/Next Actions to be Buttons (ISX-1930)

### PR DESCRIPTION
**Pull request by timkeo**
### Description

The Previous/Next Actions within the ProjectWideActions template incorrectly set to Axis types and instead should be Buttons.

### Changes made

Modified the template JSON to make Previous/Next Actions Button types and updated the fields to match other Button typed Actions.

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [x] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1882) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1882) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/InputSystem?pullRequest=1882) it.</sub>

**Review by lyndon-unity — APPROVED** [review]
Looks like the right change.
(I haven't pulled the pr to check in the editor, I'm assuming you tried reseting an existing project wide input actions asset to see it live in editor)

**Review by ekcoh — APPROVED** [review]
LGTM

**Comment by timkeo** [comment]
> Looks like the right change. (I haven't pulled the pr to check in the editor, I'm assuming you tried reseting an existing project wide input actions asset to see it live in editor)

Yes, I reset InputSystem project and created the PWA asset to verify the change in the editor.

**Review by Pauliusd01 — APPROVED** [review]

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1882) <br/>All committers have signed the CLA.

**Pull request merged**
