### PR TITLE
Update DualShockGamepadHID.cs

### PR DESCRIPTION
**Pull request by BLjung**
Sensor data format is now specified as a comment right where it needs to be added. Please add it with the correct syntax so it works with the sensor system. I really want to start using the new input system! Thanks for a great product!

### CODE REVIEW

**Comment by BLjung** [comment]
And if you want to help game developers create gyro aim:

http://gyrowiki.jibbsmart.com/blog:good-gyro-controls-part-1:the-gyro-is-a-mouse

http://gyrowiki.jibbsmart.com/blog:tight-and-smooth:soft-tiered-smoothing

Standard deviation is another algorithm that could be provided. Example:
https://github.com/Flafla2/Unity-DS4/blob/master/Assets/DS4/DS4.cs

**Comment by jimon** [comment]
Thanks for the PR @BLjung , I've added the feature request for dualshock sensors to our backlog. As this PR doesn't add the functionality I'll close it for the time being.

**Comment by eblabs** [comment]
Hi @jimon,  just wanted to follow up, did gyros for Dualshock controllers end up being added? Thanks!!

**Comment by jimon** [comment]
@eblabs hi, sorry no update as of now

**Pull request closed without merging**
