### PR TITLE
FIX: Fixed action properties editor UI (ISXB-1277)

### PR DESCRIPTION
**Pull request by bmalrat**
### Description

Action properties does not try to fit all fields by not forcing a minimum size

### Testing status & QA
base IMGUI :
Screenshot 2024-12-03 165758

before UI Toolkit: 
Screenshot 2024-12-04 103135

tested with 2022.3 and 6000.0 now UI Toolkit:
Screenshot 2024-12-09 112440

### Overall Product Risks

_Please rate the potential complexity and halo effect from low to high for the reviewers. Note down potential risks to specific Editor branches if any._

- Complexity: 0
- Halo Effect: 0

### Comments to reviewers

_Please describe any additional information such as what to focus on, or historical info for the reviewers._

### Checklist

Before review:

- [X ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.
    - Jira port for the next release set as "Resolved".
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

### CODE REVIEW

**Review by lyndon-unity — APPROVED** [review]
Looks like a reasonable change to fix the formatting.

**Comment by Pauliusd01** [comment]
With the minimum action window size the panel is still too small. Maybe requires upping that window minimum as well?
image

**Comment by bmalrat** [comment]
> With the minimum action window size the panel is still too small. Maybe requires upping that window minimum as well? image

Good catch I updated it

**Review by Pauliusd01 — APPROVED** [review]
LGTM, checked it in the PWA view and custom input actions window. I did notice one small thing, the draggable action properties line gets thicker when the panel is at its max size (see video) but it seems so minor I wouldn't mind if It's kept as is 

https://github.com/user-attachments/assets/5c6c9151-aee9-420d-aab4-d1cd55a9af52

**Pull request merged**
