### PR TITLE
FIX: Asset processor issues ISX-1885 ISX-1887

### PR DESCRIPTION
**Pull request by ekcoh**
### Description

FIX: Addressed problems in AssetPostProcessor in InputActionImporter causing worker thread issues and causing editor assets to get wiped.

### Changes made

Writing directly to asset file without checking out the file and without reimport seems to cause issues. Hence this was modified to use a common routine which also reduces duplicated code. In addition did some refactoring related to asset extension to remove some redundant logic since relevant for the updated logic in the processor.

### Notes

Intends to solve ISX-1885 and ISX-1887. I have additional updates to asset management, processors and editor behavior related to changes to input actions assets in a pending PR, but decided to isolate these fixes into its own PR and let it go in first. Other PR is here for reference (WIP) https://github.com/Unity-Technologies/InputSystem/pull/1850

No changelog entry added since this is just modifying internals to fix a regression/problem with previous PR: https://github.com/Unity-Technologies/InputSystem/pull/1836

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

### CODE REVIEW

**Review by Pauliusd01 — APPROVED** [review]
LGMT, I tested manual and auto saving for different assets, how auto save interacts with Editor deselection and quickly double checked actual functionality in the sample scenes. Do let me know if there's anything else that I've missed though

**Comment by ekcoh** [comment]
> LGMT, I tested manual and auto saving for different assets, how auto save interacts with Editor deselection and quickly double checked actual functionality in the sample scenes. Do let me know if there's anything else that I've missed though

Sounds good, the real testing effort comes with the follow up branch/POR. If this resolved the two mentioned bugs then we are good.

**Comment by Pauliusd01** [comment]
> > LGMT, I tested manual and auto saving for different assets, how auto save interacts with Editor deselection and quickly double checked actual functionality in the sample scenes. Do let me know if there's anything else that I've missed though
> 
> Sounds good, the real testing effort comes with the follow up branch/POR. If this resolved the two mentioned bugs then we are good.

Yes it has, no longer seeing the warnings and the saving worked as it did before the regressions.

**Review by graham-huws — APPROVED** [review]
LGTM, definitely like the change with IsInputActionAssetPath!

**Pull request merged**
