### PR TITLE
FIX: Submit and Cancel actions should obey configured interactions.

### PR DESCRIPTION
**Pull request by smnwttbr**
### Description

Submit and Cancel actions were always triggered on a press event, even if the interaction was configured as ReleaseOnly. This PR changes that so that Interactions are respected. [ISXB-841](https://issuetracker.unity3d.com/product/unity/issues/guid/ISXB-841)

### Changes made

InputSystemUIInputModule was changed to use WasPerformedThisFrame() instead of WasPressedThisFrame().

### Testing

Tested manually using project supplied in Jira.

### Risk

These changes are fundamental to how the submit and cancel actions are triggered. Any projects relying on the old behaviour will be disrupted.

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.	
    - Jira port for the next release set as "Resolved".
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

### CODE REVIEW

**Review by ekcoh — APPROVED** [review]
Changes look good to me, suggest just getting a sanity check from @benoitalain or @bmalrat on this one in case of side effects. Would be awesome if it could be covered by an automated test as well (if not already covered by a test in UITests.cs).

**Comment by ekcoh** [comment]
Added @stefanunity for QA assessment.

**Comment by bmalrat** [comment]
> Changes look good to me, suggest just getting a sanity check from @benoitalain or @bmalrat on this one in case of side effects. Would be awesome if it could be covered by an automated test as well (if not already covered by a test in UITests.cs).

Seems good for me, I don't see any side effects for that one

**Review by stefanunity — APPROVED** [review]

**Comment by ekcoh** [comment]
@smnwttbr I only believe conflicts need to be resolved and then I think you may merge this.

**Comment by ekcoh** [comment]
I fixed the conflict in CHANGELOG.md and also moved the message from CHANGE to FIX since this was a bug report and behavior didn't do what it was supposed to. Let me know if you think it was an incorrect call.

**Pull request merged**
