### PR TITLE
FIX: Gravity, LinearAcceleration, and Attitude not initialized on iOS (case 1251382).

### PR DESCRIPTION
**Pull request by Rene-Damm**
Fixes [1251382](https://issuetracker.unity3d.com/product/unity/issues/guid/1251382/) ([internal](https://fogbugz.unity3d.com/f/cases/1251382/)).

### CODE REVIEW

**Review by todi1856 — APPROVED** [review]
Looks good, but QA needs to verify

**Comment by Rene-Damm** [comment]
> Looks good, but QA needs to verify

Yup, expecting that to happen as part of verification for the closed ticket when the next package comes out.

**Comment by todi1856** [comment]
> > Looks good, but QA needs to verify
> 
> Yup, expecting that to happen as part of verification for the closed ticket when the next package comes out.

Can't QA clone this branch and test? I thought we test first, then release, not the opposite :)

**Review by aleksandrasdzikia — APPROVED** [review]
All three now are initialised on iOS, issue seems to be fixed.

**Review by karljj1 — APPROVED** [review]

**Pull request merged**
