### PR TITLE
Added a warning when a generated class is being finalized but an InputActionMap is left enabled.

### PR DESCRIPTION
**Pull request by peterhall-unity3d**
Added a warning when a generated class is being finalized but an InputActionMap is left enabled.

If it's left enabled that could lead to the StateChangeMonitorsForDevice.listeners growing. As it grows performance of input events will get worse.

I'm open to the idea that there might be a better way to deal with this - if you can think of a good alternative please let me know!

### Description

Working towards fixing ISX-1357 - https://jira.unity3d.com/browse/ISX-1357.  This change should warn users if they create an instance of a generated C# class, enable action maps, and the C# class is then finalized with the action map still enabled.

### Changes made

Added a finalizer to the generated class that asserts all the action maps are not enabled, with a message telling the user which action maps are left enabled.

### Notes

_Please write down any additional notes, remove the section if not applicable._

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

### CODE REVIEW

**Review by lyndon-unity — APPROVED** [review]
This looks like a useful warning, but I'm wondering why we don't call Disable here to do the required work for them ?

**Review by jamesmcgill — APPROVED** [review]
lgtm

Can you add an entry in the CHANGELOG?
TVOS jobs might be a known issue but the others like formatting should pass. There is a format script in the root of the repo.
Could possibly also consider adding a test to validate that the assert triggers.

**Comment by peterhall-unity3d** [comment]
> This looks like a useful warning, but I'm wondering why we don't call Disable here to do the required work for them ?

So I did try doing this.  The problem I hit was that the finalization is running on another thread and the Disable call is not thread safe.  I considered trying to flag the item and auto-disabling it from elsewhere, though I don't think there's e.g. an Update call I can easily track that.  I guess I'm also not 100% certain that a user might somehow be relying on this behaviour and the automatic Disable call might break their project...

**Comment by lyndon-unity** [comment]
Looks like an extra file needs committing to pass the tests
Assets/Tests/InputSystem/InputActionCodeGeneratorActions.cs

**Comment by jamesmcgill** [comment]
Jobs are failing due to `error: Error building Player because scripts are compiling` issue
Needs some investigation from Input Team.

**Comment by jamesmcgill** [comment]
Thanks for the PR @peterhall-unity3d . Merged now.

**Comment by peterhall-unity3d** [comment]
> Thanks for the PR @peterhall-unity3d . Merged now.

Thank you for landing it @jamesmcgill !  🏆

**Pull request merged**
