### PR TITLE
Fixed PlayerInput not initializing UnityEvents, fixed PlayerInputEditor not saving UnityEvents

### PR DESCRIPTION
**Pull request by zadirion**
Attempting to fix issue:
https://github.com/Unity-Technologies/InputSystem/issues/500

Tested locally, fix seems to work.

### CODE REVIEW

**Comment by zadirion** [comment]
@Rene-Damm I think you're the owner of this system. I wasn't sure if unity action guids are supposed to be stored with or without {} inside the string, I assumed without, and just added the braces at call sites. Not sure what convention you had in mind. Adding them at call site is kind of ugly, so perhaps this should be abstractized somehow

**Comment by zadirion** [comment]
on an unrelated note, I noticed the system is using the old SendMessage API, I noticed there's a new messaging api out, perhaps the implementation should use that, to avoid a premature obsolescence of this code?

**Comment by Rene-Damm** [comment]
Hey @zadirion,

Thanks for the pull request!

This was indeed buggy. Looking at it, I think the whole `{...}` idea wasn't the best one and really quite unnecessary. I've created a PR that removes the entire thing (but keeps it working in existing data): https://github.com/Unity-Technologies/InputSystem/pull/509. This should hopefully fix the problem in #500.

>I noticed the system is using the old SendMessage API, I noticed there's a new messaging api out, perhaps the implementation should use that, to avoid a premature obsolescence of this code?

Which new messaging API do you have in mind?

**Comment by zadirion** [comment]
@Rene-Damm 
I'm thinking of this, although I haven't personally worked with it so far
https://docs.unity3d.com/Manual/MessagingSystem.html

**Comment by Rene-Damm** [comment]
>I'm thinking of this, although I haven't personally worked with it so far
https://docs.unity3d.com/Manual/MessagingSystem.html

Ah right. We could add support for that one as well but it would require code generation so not sure. I'm thinking that for simple prototyping, the SendMessage/Broadcast message options are good as they require zero setup. And for getting something more robust, I think the UnityEvents based notifications are probably an easier and more robust alternative to ExecuteEvents.

**Comment by zadirion** [comment]
Right. Indeed, UnityEvents also works. I have personal beef with SendMessage, as it has the nasty habit of calling into unintended methods due to name coincidence. While ok for prototyping, I don't think it should remain there, or at least not enabled by default.

**Pull request closed without merging**
