### PR TITLE
FIX: InputUser.pairedDevices getting corrupted (case 1327628).

### PR DESCRIPTION
**Pull request by Rene-Damm**
### Description

Fixes [1327628](https://issuetracker.unity3d.com/issues/input-system-devices-are-reassigned-to-the-wrong-users-after-adding-a-new-device) ([internal](https://fogbugz.unity3d.com/f/cases/1327628/)).

Pairing and unpairing devices from `InputUser`s had the potential for corrupting lists of `InputUser.pairedDevices` on users due to a nonsensical implementation of `ArrayHelpers.MoveSlice` (which slides a window of elements around in an array without requiring a temporary memory allocation).

### Changes made

Replaced the implementation of `ArrayHelpers.MoveSlice` entirely with one that recognizes that if it isn't an absolutely straightforward swapping of two array regions, then it is a simple rotation of elements within a window into the array.

Could be there's a good and proper algorithm for this that I'm ignorant of and that my Google fu failed to turn up. Had to turn this around in my head a couple times until I came up with the current solution. No proof that it's correct.

### Notes

I noticed that the existing tests in `ArrayHelperTests` were wrongly using `Is.EquivalentTo` (ignores element ordering) when they really should be using `Is.EqualTo`. Fixed that. Means that the existing test for `MoveSlice` was bogus.

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [x] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

### CODE REVIEW

**Review by andrew-oc — APPROVED** [review]
This looks like a solid implementation but I'm wondering if it's solving a problem we don't really have. The only place that MoveSlice is used is when adding devices to users right? And the bit of logic it implements there only ever moves a slice to the end of the array i.e. it doesn't have to deal with wrap around. So I'll approve the PR because it looks like it fixes the bug, but I'll suggest that we actually kill MoveSlice in this form in this PR and implement MoveSliceToEnd or something similar on the basis that it will be simpler code to maintain and will be more performant. Of course if I'm wrong about how AddDeviceToUser actually works, feel free to ignore this. That code is a bit gnarly!

**Comment by Rene-Damm** [comment]
> implement MoveSliceToEnd or something similar on the basis that it will be simpler code to maintain

Not sure it'll win us that much. Though I may totally be missing a trivially simple way to do this. In my head the "move slice to end" corresponds to the main path handled by `MoveSlice`. Elements may need to be shifted down while others need to be appended. Doing that with only single element temporary storage seems to pretty much arrive at the same code. But... maybe I'm blinded to the obvious here?

**Comment by andrew-oc** [comment]
Yeah, you're right. Not really a performance win, but simplifying the code and making the code in AddDeviceToUser more intention revealing (make it obvious that it's just moving the slice to the end) are still wins.

**Comment by Rene-Damm** [comment]
Gah, saw the comment before the edit and for a moment was hoping "haha, there *is* a much simpler way to do this!" Tried it out locally and probably came to the same conclusion you did.

Simplification RE the intent of `AddDeviceToUser` makes sense. In this case, given the implementation of the moving code will come out looking kinda identical, think I'll give up on this one.

**Comment by andrew-oc** [comment]
Actually, wish I'd left the comment in now:) You can drop destinationIndex arg and then it's just

```c#
	        var arrayLength = array.Length - 1;
	        for (int i = count - 1; i >= 0; i--)
	        {
		        Swap(ref array[sourceIndex + i], ref array[arrayLength - count + i]);
	        }
```
But yeah, not a huge win

**Comment by Rene-Damm** [comment]
> Actually, wish I'd left the comment in now:) You can drop destinationIndex arg and then it's just
> 
> ```cs
> 	        var arrayLength = array.Length - 1;
> 	        for (int i = count - 1; i >= 0; i--)
> 	        {
> 		        Swap(ref array[sourceIndex + i], ref array[arrayLength - count + i]);
> 	        }
> ```
> 
> But yeah, not a huge win

Wait, that doesn't seem to work. If we take

```
-------------------------
| 1 | 2 | 3 | 4 | 5 | 6 |
-------------------------
```

and say we want to move two elements at index 1 to the end. Then the loop above would do two swaps (`count` - 1) and give

```
-------------------------
| 1 | 5 | 6 | 4 | 2 | 3 |
-------------------------
```

**Comment by andrew-oc** [comment]
Well it was just an example :) I mean what you had in the first if branch is basically the easiest way but you can do it without the destination index if it was a 'move to end' style thing.

**Comment by Rene-Damm** [comment]
Ah heh, I see. Misunderstood :)

**Pull request merged**
