### PR TITLE
Fix XR Tests for 2019.3

### PR DESCRIPTION
**Pull request by StayTalm**
In 2019.3 Device Role got replaced with InputDeviceCharacteristics.  Updated XRTests to use Characteristics when working in 2019.3 or greater.

### CODE REVIEW

**Comment by Rene-Damm** [comment]
@karljj1 landed a change related to this as part of getting CI back to green. @StayTalm could you merge latest `develop` and update the PR? Or is it obsoleted by Karl's change?

**Comment by StayTalm** [comment]
I'll do a merge, I would like to move away from using Role since it's being deprecated, so I'm trying to set Characteristics directly instead of converting from role to characteristics.

**Comment by Rene-Damm** [comment]
> I'll do a merge, I would like to move away from using Role since it's being deprecated, so I'm trying to set Characteristics directly instead of converting from role to characteristics.

Feel free to redo/change the existing fix.

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1158) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/InputSystem?pullRequest=1158) it.</sub>

**Comment by jfreire-unity** [comment]
To be merged in #1655.

**Pull request closed without merging**
