### PR TITLE
fix: tracked device raycaster 3d occlusion hit distance calculation

### PR DESCRIPTION
**Pull request by alexboost222**
### Description

Here i made a short fix in TrackedDeviceRaycaster.cs. The issue described here https://forum.unity.com/threads/input-system-trackeddeviceraycaster-cs-3d-occlusion-check-not-working-correctly.1193089/. In two words: there was a bug in 3d occlusion check while raycasting UI.

### Changes made

Changed calculation of hitDistance local variable in internal PerformRaycast method of TrackedDeviceRaycaster.cs

### Notes

It was my first fork and PR ever. Hope it will be applied!)

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [x] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [x] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1458) <br/>All committers have signed the CLA.

**Comment by alexboost222** [comment]
How can i generate a ticket on unity issue tracker to attach it here?

**Comment by ekcoh** [comment]
Thanks for the submitted fix @alexboost222. In order to generate a unity issue tracker related to this, you may file the issue via the bug reporting functionality in the editor, see: https://unity3d.com/unity/qa/bug-reporting

**Comment by alexboost222** [comment]
@ekcoh submitted the bug report using suggested functionality in the editor, attached project with recreated reproducing case and received an email with case number 1379298. Also there was a link on https://fogbugz.unity3d.com, not on the issuetracker.unity3d.com. What should i do next?

**Comment by alexboost222** [comment]
Hi! Is there any progress in resolving the issue?

**Comment by alexboost222** [comment]
@Rene-Damm tagged you because you have the most activity on the forum and youtube on the input system topic, can u please look at this PR and tell what else should i do to make it merged

**Comment by Rene-Damm** [comment]
Thank you for the fix. Integrated and merged as part of #1477.

**Pull request closed without merging**
