### PR TITLE
FIX: Update OnScreenStick.cs

### PR DESCRIPTION
**Pull request by ghost**
### Description

Fix memory leak - make sure to unsubscribe started, and canceled actions for m_PointerDownAction on destroy when m_UseIsolatedInputActions is set to true.

### Changes made

Added private method OnDestroy.

### Testing

Fore testing is required to add OnScreenStick component and check UseIsolatedInputActions, and setup for-example Hold interaction there.

### Risk

There is no risk.

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1960) <br/>All committers have signed the CLA.

**Review by ekcoh — CHANGES_REQUESTED** [review]
Thanks for providing this fix @LukeUnityDev. It would be great if you could add a line to the CHANGELOG.md file describing under title fixed for unreleased version that a memory leak has been adressed in OnScreenStick which would leak memory when component was destroyed. When this have been updated we can land the contribution.

**Comment by ghost** [comment]
@ekcoh thank you for review, I have added

**Comment by ekcoh** [comment]
Seems problematic to land from fork. I rerouted your fix via https://github.com/Unity-Technologies/InputSystem/pull/2006 and marked your contrib in the CHANGELOG so will close this PR and let the other land when reviewed and approved by the team. Thanks @LukeUnityDev

**Pull request closed without merging**
