### PR TITLE
Added to generated C# wrapper action maps support for subscribing mul…

### LINKED ISSUE #823: Add a ClearCallbacks generated interface method
This method does the exact opposite of `SetCallbacks` ~~--~~ unsubscribes the given instance from the callbacks ~~--~~, although it might have some design issues.

The reason I need this is to be able to make a global input manager instead of having several instances of a generated class all over my code. A global input manager should make it easier to control action maps. However, to do this, I need to be able to unsubscribe classes from the events in `OnDisable`. Right now, we can just disable the action map in the instance, but there's no practical way to unsubscribe from the events.

Actually, now that I think about it, there might not actually be many problems with it. I might try to implement it myself.

### PR DESCRIPTION
**Pull request by Ramobo**
…tiple interfaces and a ClearCallbacks method

Closes #823.

### CODE REVIEW

**Comment by Ramobo** [comment]
Is there something wrong here? An issue that needs my attention? It's been 12 days and nothing.

**Comment by Rene-Damm** [comment]
Sorry to leave you hanging.

ATM we're not merging feature PRs in order to not rock the boat for 1.0. Once 1.0 out for good (shouldn't be too long), we'll open the develop branch back up for feature work.

As far as the changes here go, I think it makes sense to extend the generated code to allow multiple receivers. Not exactly this way but something along the lines. Something to look at 
I don't think this is quite the right change. At least not at this point, after 1.0 is out, I think it makes sense to consider a change to the code generator.

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=889) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=889) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/InputSystem?pullRequest=889) it.</sub>

**Comment by ekcoh** [comment]
Closing this PR since a similar change have been routed via https://github.com/Unity-Technologies/InputSystem/pull/1593. It was slightly modified to not break backwards compability. Thanks for your contribution and it has been mentioned in the CHANGELOG.md.

**Pull request closed without merging**
