### PR TITLE
FIX: Fixed pasting bindings into empty Input Action asset (case ISXB-1180) - take #2

### PR DESCRIPTION
**Pull request by AlexTyrer**
### Description

Null Reference Exceptions errors could be logged to the console window when pasting items into the Input Actions Editor window.

FIX: Fixed pasting bindings into empty Input Action asset (case ISXB-1180)
FIX: Fixed pasting newly created Action Map when copied from  from Project Settings to new Input Action Asset (case ISXB-1182)

Several issues were addressed:

- Ensure PasteBlocks() deals with invalid selection - when copied type is binding we need to have a valid Action selected to paste into.
- Improved the context menu population in the Input Actions Editor window (Action Maps and Action views):
  o Ensure Paste option is only present in context menu when appropriate.
  o Fix menu separator presence (or absense).
  o Action Maps view: can Paste ActionMap or Action (if a map is present).
  o Actions view: can paste Actions or Bindings depending on selected item context.

### Testing status & QA

Local testing / automated tests.

### Overall Product Risks

Relatively small - only affects the context menu in the Input Actions Editor window.

Complexity: 0
Halo Effect: 0

### Comments to reviewers

None in particular - I tried lots of copy / paste with various selections & no selection made, including after deleting an item previously selected.

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.
    - Jira port for the next release set as "Resolved".
- [x] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [x] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

### CODE REVIEW

**Comment by Pauliusd01** [comment]
The error is gone but I'm still allowed to paste it and it pastes it into the void

https://github.com/user-attachments/assets/79cb3957-4265-48a8-9ca3-09eb88cd3bb3

**Comment by AlexTyrer** [comment]
> Action selected to paste into.

Yea, there's a few places where stuff like that happens - I'm not sure yet where the context menu gets updated (it shouldn't be on the menu really when there's no valid target).

**Review by Pauliusd01 — CHANGES_REQUESTED** [review]
Updating status

**Comment by AlexTyrer** [comment]
> > Action selected to paste into.
> 
> Yea, there's a few places where stuff like that happens - I'm not sure yet where the context menu gets updated (it shouldn't be on the menu really when there's no valid target).

I've discussed this with Rita after having identified a few more inconsistencies with the context menu.

Now I better understand where this menu gets updated I will now make a pass through the code and make the context menu behaviour more consistent.

**Comment by AlexTyrer** [comment]
@Pauliusd01 I've reworked a lot of the context menu and Copy/Paste behaviour so it's more consistent.

Would really appreciate you testing it out.

Branch: **isxb-1180/fix-paste-bindings-from-clipboard-2**

**Review by Pauliusd01 — APPROVED** [review]
LGTM, checked cutting/copying bindings, actions and maps into various situations (empty list, invalid list, clicking outside of selection, etc) 

_I did find a bug with composite bindings being able to be pasted into non composite actions and then once pasted they disappear but that is also in stable and unrelated to this PR._

**Comment by AlexTyrer** [comment]
> LGTM, checked cutting/copying bindings, actions and maps into various situations (empty list, invalid list, clicking outside of selection, etc)
> 
> _I did find a bug with composite bindings being able to be pasted into non composite actions and then once pasted they disappear but that is also in stable and unrelated to this PR._

Thanks Paulius, appreciate the time and effort.

I'm not surprised there's a few more niggles to shake out in there (I didn't pay much attention to the composite stuff) - it feels more solid to me now with these changes and I've been able to close out a couple more bugs with the fixes.

**Pull request merged**
